/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/alunos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gestor vê lista de alunos cadastrados */
        get: operations["list_alunos_gestor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alunos/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Aluno atualiza seu perfil (Dados Pessoais + Endereço) */
        put: operations["aluno_profile"];
        post?: never;
        /** Aluno exclui sua conta */
        delete: operations["aluno_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alunos/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auto-cadastro do Aluno (Público) */
        post: operations["aluno_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request password recovery
         * @description Sends email with reset link if the user exists.
         */
        post: operations["auth_forgot_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate user and get JWT token
         * @description Use the returned token in the `Authorization` header for authenticated requests:
         *     `Authorization: Bearer <token>`
         */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/relatorios/periodo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gera o relatório operacional de um período */
        get: operations["relatorio_periodo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/viagens/{viagem_id}/progresso": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viagem_id: string;
            };
            cookie?: never;
        };
        /** Obtém o progresso de uma viagem (os pontos fixos visitados) */
        get: operations["progresso_viagem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/viagens/{viagem_id}/trajeto-real": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viagem_id: string;
            };
            cookie?: never;
        };
        /** Obtém o rastro GPS completo (trajeto real) de uma viagem */
        get: operations["trajeto_real_viagem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instituicoes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_instituicoes"];
        put?: never;
        /** Cadastra uma nova instituição com endereço */
        post: operations["create_instituicao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instituicoes/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_instituicoes_public"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instituicoes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["get_instituicao"];
        put?: never;
        post?: never;
        delete: operations["delete_instituicao"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notificacoes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as notificações do usuário logado */
        get: operations["listar_minhas_notificacoes"];
        put?: never;
        /** (Gestor) Envia um aviso para Rota ou Viagem */
        post: operations["gestor_enviar_notificacao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notificacoes/{id}/lida": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marca uma notificação como lida */
        patch: operations["marcar_notificacao_lida"];
        trace?: never;
    };
    "/v1/onibus/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista a frota da prefeitura */
        get: operations["list_onibus"];
        put?: never;
        /** Cadastra um novo ônibus */
        post: operations["create_onibus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/onibus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Detalhes de um ônibus */
        get: operations["get_onibus"];
        put?: never;
        post?: never;
        /** Remove um ônibus */
        delete: operations["delete_onibus"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pontos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_pontos"];
        put?: never;
        post: operations["create_ponto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pontos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["get_ponto"];
        put: operations["update_ponto"];
        post?: never;
        delete: operations["delete_ponto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rotas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_rotas"];
        put?: never;
        post: operations["create_rota"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rotas/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_my_rotas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rotas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["get_rota"];
        put: operations["update_rota"];
        post?: never;
        delete: operations["delete_rota"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rotas/{id}/horarios": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["list_rota_horarios"];
        put?: never;
        post: operations["add_rota_horario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rotas/{id}/inscricao": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID da Rota */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inscrever_aluno"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rotas/{id}/pontos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["list_rota_pontos"];
        put?: never;
        post: operations["add_rota_pontos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todos os usuários da prefeitura (Apenas Gestor) */
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/alunos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gestor provisiona uma nova conta de aluno */
        post: operations["aluno_provision_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Altera a senha do usuário logado (Requer senha atual) */
        post: operations["change_user_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/fcm-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza o Token do Firebase (Push Notifications) do aparelho do usuário */
        patch: operations["update_fcm_token"];
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil do usuário logado */
        get: operations["get_my_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/motoristas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista motoristas do mesmo município do Gestor */
        get: operations["list_motoristas"];
        put?: never;
        /** Gestor cria um novo Motorista */
        post: operations["create_motorista"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description O UUID do usuário */
                id: string;
            };
            cookie?: never;
        };
        /** Busca usuário por ID (próprio perfil ou mesma prefeitura se Gestor) */
        get: operations["get_user_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viagens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_all_viagens"];
        put?: never;
        post: operations["create_viagem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viagens/aluno/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_viagens_aluno"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viagens/gerar-lote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["gerar_viagens_lote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viagens/minhas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_my_viagens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viagens/{id}/acao": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["control_viagem"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viagens/{id}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Cancela uma viagem agendada e notifica alunos (Gestor) */
        put: operations["cancelar_viagem"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viagens/{id}/confirmacao": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["confirmar_presenca"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viagens/{id}/localizacao": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** (Aluno/Motorista) Obtém a localização atual do ônibus (viagem em andamento) */
        get: operations["obter_localizacao_onibus"];
        put?: never;
        /** (Motorista) Envia coordenada GPS atual do ônibus em tempo real */
        post: operations["atualizar_localizacao_onibus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viagens/{id}/pontos-embarque": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Lista todos os pontos de embarque disponíveis para esta viagem */
        get: operations["list_pontos_embarque_viagem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viagens/{viagem_id}/localizacao-aluno": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viagem_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recebe o GPS em tempo real do Aluno para o Auto-Checkin (Geofencing) */
        post: operations["atualizar_localizacao_aluno"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** @description Email do usuário */
            email: string;
            /** @description Senha */
            password: string;
        };
        TokenResponse: {
            /** @description Mensagem de sucesso */
            message?: string;
            /** @description JWT Token */
            token?: string;
            /** @description Dados do usuário */
            user?: components["schemas"]["UserInfo"];
        };
        UserInfo: {
            /** @description ID do usuário */
            id?: string;
            /** @description Nome do usuário */
            nome?: string;
            /** @description Email do usuário */
            email?: string;
            /** @description Perfil do usuário */
            role?: string;
        };
        ForgotPasswordRequest: {
            /** @description Email para recuperação de senha */
            email: string;
        };
        UserListResponse: {
            items?: components["schemas"]["UserResponse"][];
            /** @description Total de usuários */
            total?: number;
        };
        UserResponse: {
            /** @description UUID do usuário */
            id?: string;
            /** @description UUID da prefeitura */
            prefeitura_id?: string;
            /** @description Nome completo */
            nome?: string;
            /** @description Email */
            email?: string;
            /** @description Telefone */
            telefone?: string;
            /** @description CPF */
            cpf?: string;
            /** @description Perfil (ALUNO, MOTORISTA, GESTOR) */
            role?: string;
            /** @description Status (PENDING_SIGNUP, ACTIVE, DISABLED) */
            status?: string;
            /**
             * Format: date-time
             * @description Data de conclusão do cadastro
             */
            signup_completed_at?: string;
            /** @description Nome do município (prefeitura) */
            municipio_nome?: string;
            /** @description UF do município */
            municipio_uf?: string;
            /** @description Matrícula (aluno) */
            matricula?: string;
            /** @description Nome do pai (aluno) */
            nome_pai?: string;
            /** @description Nome da mãe (aluno) */
            nome_mae?: string;
            /** @description CNH (motorista) */
            cnh?: string;
        };
        AlunoProvisionAccountRequest: {
            /** @description Nome completo */
            nome: string;
            /** @description Email */
            email: string;
            /** @description Senha */
            password: string;
            /** @description CPF */
            cpf: string;
            /** @description Telefone */
            telefone?: string;
        };
        MotoristaCreateRequest: {
            /** @description Nome completo */
            nome: string;
            /** @description Email */
            email: string;
            /** @description Senha */
            password: string;
            /** @description CPF */
            cpf: string;
            /** @description Telefone */
            telefone?: string;
            /** @description CNH */
            cnh: string;
            /** @description Salário */
            salario?: number;
        };
        ChangePasswordRequest: {
            /** @description Senha atual */
            current_password: string;
            /** @description Nova senha */
            new_password: string;
        };
        ChangePasswordResponse: {
            /** @description Mensagem de sucesso */
            message?: string;
        };
        FcmTokenRequest: {
            /** @description Token do dispositivo gerado pelo Firebase no Frontend */
            fcm_token: string;
        };
        NotificacaoInput: {
            /**
             * @description Título do aviso
             * @example Aviso Importante
             */
            titulo: string;
            /**
             * @description Corpo da mensagem
             * @example O ônibus vai atrasar 10 minutos hoje.
             */
            mensagem: string;
            /**
             * @description ID da rota (opcional se enviar viagem_id)
             * @example COLE_O_UUID_DA_ROTA_AQUI
             */
            rota_id?: string;
            /**
             * @description ID da viagem (opcional)
             * @example
             */
            viagem_id?: string;
        };
        OnibusCreateRequest: {
            /** @description Placa do veículo */
            placa: string;
            /** @description Modelo */
            modelo?: string;
            /** @description Capacidade de passageiros */
            capacidade?: number;
            /** @description Ano de fabricação */
            ano?: number;
        };
        OnibusListResponse: {
            items?: components["schemas"]["OnibusResponse"][];
            /** @description Total de ônibus */
            total?: number;
        };
        OnibusResponse: {
            /** @description UUID do ônibus */
            id?: string;
            /** @description Placa */
            placa?: string;
            /** @description Modelo */
            modelo?: string;
            /** @description Capacidade */
            capacidade?: number;
            /** @description Ano */
            ano?: number;
        };
        RotaCreateRequest: {
            /** @description Nome da rota */
            nome: string;
            /** @description UUID do motorista padrão */
            motorista_padrao_id?: string;
            /** @description UUID do veículo padrão */
            veiculo_padrao_id?: string;
            /** @description Pontos da rota */
            pontos?: components["schemas"]["RotaPontoAddRequest"][];
            /** @description Grade de horários */
            horarios?: components["schemas"]["RotaHorarioCreateRequest"][];
        };
        RotaPontoAddRequest: {
            /** @description UUID do ponto */
            ponto_id: string;
            /** @description Ordem na rota */
            ordem: number;
        };
        RotaHorarioCreateRequest: {
            /** @description Horário (HH:MM) */
            horario_saida: string;
            /** @description IDA, VOLTA ou CIRCULAR */
            sentido: string;
            /** @description Dias da semana (SEG, TER, ...) */
            dias: string[];
        };
        RotaListResponse: {
            items?: components["schemas"]["RotaResponse"][];
            /** @description Total de rotas */
            total?: number;
        };
        RotaResponse: {
            /** @description UUID */
            id?: string;
            /** @description Nome */
            nome?: string;
            /** @description UUID do motorista padrão */
            motorista_id?: string;
            /** @description UUID do veículo padrão */
            veiculo_id?: string;
            /** @description UUID da prefeitura */
            prefeitura_id?: string;
            /** @description Nome do município */
            municipio_nome?: string;
            /** @description UF do município */
            municipio_uf?: string;
        };
        RotaInscricaoRequest: {
            /** @description inscrever ou desinscrever */
            acao: string;
        };
        PontoFlatListResponse: {
            items?: components["schemas"]["PontoFlatResponse"][];
            /** @description Total de pontos */
            total?: number;
        };
        PontoFlatResponse: {
            /** @description UUID do ponto */
            id?: string;
            /** @description Nome/apelido */
            apelido?: string;
            /** @description Latitude */
            latitude?: number;
            /** @description Longitude */
            longitude?: number;
            /** @description Ordem */
            ordem?: number;
        };
        RotaHorarioListResponse: {
            items?: components["schemas"]["RotaHorarioResponse"][];
            /** @description Total de horários */
            total?: number;
        };
        RotaHorarioResponse: {
            /** @description UUID */
            id?: string;
            /** @description Horário */
            horario_saida?: string;
            /** @description Sentido */
            sentido?: string;
            /** @description Dias */
            dias?: string[];
        };
        RotaUpdateRequest: {
            /** @description Nome da rota */
            nome: string;
            /** @description UUID do motorista padrão */
            motorista_padrao_id?: string;
            /** @description UUID do veículo padrão */
            veiculo_padrao_id?: string;
            /** @description Pontos da rota */
            pontos?: components["schemas"]["RotaPontoAddRequest"][];
            /** @description Grade de horários */
            horarios?: components["schemas"]["RotaHorarioCreateRequest"][];
        };
        RotaDetailResponse: {
            /** @description UUID */
            id?: string;
            /** @description Nome */
            nome?: string;
            /** @description UUID do motorista padrão */
            motorista_id?: string;
            /** @description UUID do veículo padrão */
            veiculo_id?: string;
            /** @description UUID da prefeitura */
            prefeitura_id?: string;
            /** @description Nome do município */
            municipio_nome?: string;
            /** @description UF do município */
            municipio_uf?: string;
            pontos?: components["schemas"]["PontoFlatResponse"][];
            horarios?: components["schemas"]["RotaHorarioResponse"][];
        };
        PontoCreateRequest: {
            /** @description Nome do ponto (ex: Escola A) */
            apelido?: string;
            /** @description Latitude */
            latitude: number;
            /** @description Longitude */
            longitude: number;
        };
        PontoListResponse: {
            items?: components["schemas"]["PontoResponse"][];
            /** @description Total de pontos */
            total?: number;
        };
        PontoResponse: {
            /** @description UUID do ponto */
            id?: string;
            /** @description Nome/apelido */
            apelido?: string;
            /** @description Latitude */
            latitude?: number;
            /** @description Longitude */
            longitude?: number;
            /** @description Endereço formatado */
            endereco?: string;
            /** @description Instituição vinculada */
            instituicao?: string;
        };
        PontoUpdateRequest: {
            /** @description Nome do ponto (ex: Escola A) */
            apelido?: string;
            /** @description Latitude */
            latitude?: number;
            /** @description Longitude */
            longitude?: number;
        };
        ViagemAgendaAlunoListResponse: {
            items?: components["schemas"]["ViagemAgendaAlunoResponse"][];
            /** @description Total de viagens */
            total?: number;
        };
        ViagemAgendaAlunoResponse: {
            /** @description UUID da viagem */
            viagem_id?: string;
            /** @description Data */
            data?: string;
            /** @description Dia da semana */
            dia_semana?: string;
            /** @description Horário */
            horario_saida?: string;
            /** @description Sentido */
            sentido?: string;
            /** @description UUID da rota */
            rota_id?: string;
            /** @description Nome da rota */
            rota_nome?: string;
            /** @description Confirmado */
            status_confirmacao?: boolean;
            /** @description UUID do ponto de embarque */
            ponto_embarque_id?: string;
        };
        ViagemConfirmacaoRequest: {
            /** @description Confirmado */
            confirmacao: boolean;
            /** @description UUID do ponto de embarque (opcional) */
            ponto_embarque_id?: string;
        };
        ViagemAlunoConfirmacaoResponse: {
            /** @description UUID do aluno */
            aluno_id?: string;
            /** @description Nome do aluno */
            nome?: string;
            /** @description Confirmado */
            confirmacao?: boolean;
            /** @description UUID do ponto de embarque */
            ponto_embarque?: string;
        };
        ViagemCreateRequest: {
            /** @description UUID da rota */
            rota_id: string;
            /** @description UUID do horário */
            horario_id: string;
            /** @description Data (YYYY-MM-DD) */
            data: string;
            /** @description UUID do motorista (opcional) */
            motorista_id?: string;
            /** @description UUID do veículo (opcional) */
            veiculo_id?: string;
        };
        ViagemListResponse: {
            items?: components["schemas"]["ViagemResponse"][];
            /** @description Total de viagens */
            total?: number;
        };
        ViagemResponse: {
            /** @description UUID */
            id?: string;
            /** @description Data */
            data?: string;
            /** @description Horário */
            horario_saida?: string;
            /** @description Sentido */
            sentido?: string;
            /** @description AGENDADA, EM_ANDAMENTO, FINALIZADA */
            status?: string;
            /** @description UUID da rota */
            rota_id?: string;
            /** @description Nome da rota */
            rota_nome?: string;
            /** @description UUID do motorista */
            motorista_id?: string;
            /** @description UUID do veículo */
            veiculo_id?: string;
        };
        ViagemLoteRequest: {
            /** @description Data para gerar viagens (YYYY-MM-DD) */
            data: string;
        };
        ViagemLoteResponse: {
            /** @description Total de rotas analisadas */
            total_rotas_analisadas?: number;
            /** @description Total de viagens criadas */
            viagens_criadas?: number;
            detalhes?: string[];
        };
        ViagemAcaoRequest: {
            /** @description iniciar ou finalizar */
            acao: string;
        };
        LocalizacaoRequest: {
            /** @description Latitude atual do ônibus */
            latitude: number;
            /** @description Longitude atual do ônibus */
            longitude: number;
        };
        InstituicaoListResponse: {
            items?: components["schemas"]["InstituicaoResponse"][];
            /** @description Total de instituições */
            total?: number;
        };
        InstituicaoResponse: {
            /** @description UUID */
            id?: string;
            /** @description Nome */
            nome?: string;
            /** @description Tipo */
            tipo?: string;
            /** @description Endereço formatado */
            endereco?: string;
        };
        InstituicaoCreateRequest: {
            /** @description Nome da instituição */
            nome: string;
            /** @description Tipo (ESCOLA, CRECHE, UNIVERSIDADE) */
            tipo?: string;
            /** @description Endereço */
            endereco: components["schemas"]["InstituicaoEnderecoInput"];
        };
        InstituicaoEnderecoInput: {
            /** @description Nome da rua */
            rua?: string;
            /** @description Número */
            numero?: string;
            /** @description Bairro */
            bairro?: string;
            /** @description Cidade */
            cidade?: string;
            /** @description Estado (UF) */
            estado?: string;
            /** @description CEP */
            cep?: string;
        };
        AlunoSelfSignupRequest: {
            /** @description Nome completo */
            nome: string;
            /** @description Email */
            email: string;
            /** @description Senha */
            password: string;
            /** @description CPF */
            cpf: string;
            /** @description Telefone */
            telefone?: string;
            /** @description Matrícula escolar */
            matricula: string;
            /** @description UUID da instituição */
            instituicao_id: string;
            /** @description Nome do pai */
            nome_pai?: string;
            /** @description CPF do pai */
            cpf_pai?: string;
            /** @description Nome da mãe */
            nome_mae?: string;
            /** @description CPF da mãe */
            cpf_mae?: string;
            endereco_casa: components["schemas"]["EnderecoInput"];
        };
        EnderecoInput: {
            /** @description Nome da rua */
            rua: string;
            /** @description Número */
            numero: string;
            /** @description Bairro */
            bairro: string;
            /** @description Cidade */
            cidade: string;
            /** @description Estado (UF) */
            estado: string;
            /** @description CEP */
            cep: string;
            /** @description Complemento */
            complemento?: string;
        };
        AlunoResponse: {
            /** @description UUID do aluno */
            id?: string;
            /** @description Nome completo */
            nome?: string;
            /** @description Matrícula */
            matricula?: string;
            /** @description Nome da escola */
            escola?: string;
            /** @description Status (PENDING_SIGNUP, ACTIVE, DISABLED) */
            status?: string;
            /**
             * Format: date-time
             * @description Data de conclusão do cadastro
             */
            signup_completed_at?: string;
        };
        AlunoMeUpdateRequest: {
            /** @description Nome completo */
            nome?: string;
            /** @description Telefone */
            telefone?: string;
            /** @description Matrícula escolar */
            matricula?: string;
            /** @description Nome do pai */
            nome_pai?: string;
            /** @description CPF do pai */
            cpf_pai?: string;
            /** @description Nome da mãe */
            nome_mae?: string;
            /** @description CPF da mãe */
            cpf_mae?: string;
            endereco_casa?: components["schemas"]["EnderecoInput"];
        };
        AlunoListResponse: {
            items?: components["schemas"]["AlunoResponse"][];
            /** @description Total de alunos */
            total?: number;
        };
        PontoProgresso: {
            /** @description ID do ponto */
            ponto_id?: string;
            /** @description Nome/Apelido do ponto */
            apelido?: string;
            /** @description Horário real da passagem (ISO) */
            horario_passagem?: string;
        };
        RelatorioEstatisticas: {
            /** @description Período analisado */
            periodo?: string;
            /** @description Total de viagens finalizadas */
            viagens_realizadas?: number;
            /** @description Total de embarques reais */
            alunos_transportados?: number;
            /** @description Alunos que confirmaram mas não embarcaram */
            vagas_desperdicadas?: number;
            /** @description Quilometragem total gasta */
            km_total_rodado?: number;
            /** @description Eficiência da operação */
            media_alunos_por_km?: number;
        };
        PontoTelemetria: {
            /** @description Latitude */
            latitude?: number;
            /** @description Longitude */
            longitude?: number;
            /** @description Horário exato do registro (ISO) */
            timestamp?: string;
        };
    };
    responses: {
        /** @description When a mask can't be parsed */
        ParseError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description When any error occurs on mask */
        MaskError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: {
        LocalizacaoRequest: {
            content: {
                "application/json": components["schemas"]["LocalizacaoRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_alunos_gestor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlunoListResponse"];
                };
            };
        };
    };
    aluno_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlunoMeUpdateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlunoResponse"];
                };
            };
        };
    };
    aluno_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aluno_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlunoSelfSignupRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlunoResponse"];
                };
            };
        };
    };
    auth_forgot_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description If request accepted (email sent if user exists) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid email format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful - returns JWT token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many login attempts - rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    relatorio_periodo: {
        parameters: {
            query: {
                /** @description Data de início do relatório (YYYY-MM-DD) */
                data_inicio: string;
                /** @description Data de fim do relatório (YYYY-MM-DD) */
                data_fim: string;
            };
            header?: {
                /** @description An optional fields mask */
                "X-Fields"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatorioEstatisticas"];
                };
            };
        };
    };
    progresso_viagem: {
        parameters: {
            query?: never;
            header?: {
                /** @description An optional fields mask */
                "X-Fields"?: string;
            };
            path: {
                viagem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoProgresso"][];
                };
            };
        };
    };
    trajeto_real_viagem: {
        parameters: {
            query?: never;
            header?: {
                /** @description An optional fields mask */
                "X-Fields"?: string;
            };
            path: {
                viagem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoTelemetria"][];
                };
            };
        };
    };
    list_instituicoes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstituicaoListResponse"];
                };
            };
        };
    };
    create_instituicao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstituicaoCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstituicaoResponse"];
                };
            };
        };
    };
    list_instituicoes_public: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstituicaoListResponse"];
                };
            };
        };
    };
    get_instituicao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstituicaoResponse"];
                };
            };
        };
    };
    delete_instituicao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listar_minhas_notificacoes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestor_enviar_notificacao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificacaoInput"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    marcar_notificacao_lida: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_onibus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnibusListResponse"];
                };
            };
        };
    };
    create_onibus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnibusCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnibusResponse"];
                };
            };
        };
    };
    get_onibus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnibusResponse"];
                };
            };
        };
    };
    delete_onibus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_pontos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoListResponse"];
                };
            };
        };
    };
    create_ponto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PontoCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoResponse"];
                };
            };
        };
    };
    get_ponto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoResponse"];
                };
            };
        };
    };
    update_ponto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PontoUpdateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoResponse"];
                };
            };
        };
    };
    delete_ponto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_rotas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotaListResponse"];
                };
            };
        };
    };
    create_rota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotaCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotaResponse"];
                };
            };
        };
    };
    list_my_rotas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotaListResponse"];
                };
            };
        };
    };
    get_rota: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotaDetailResponse"];
                };
            };
        };
    };
    update_rota: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotaUpdateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_rota: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_rota_horarios: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotaHorarioListResponse"];
                };
            };
        };
    };
    add_rota_horario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotaHorarioCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotaHorarioResponse"];
                };
            };
        };
    };
    inscrever_aluno: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID da Rota */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotaInscricaoRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_rota_pontos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoFlatListResponse"];
                };
            };
        };
    };
    add_rota_pontos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotaPontoAddRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Forbidden - not a gestor */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aluno_provision_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlunoProvisionAccountRequest"];
            };
        };
        responses: {
            /** @description Aluno account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not a gestor */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict - duplicate email/CPF */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_user_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Incorrect current password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many attempts - rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_fcm_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FcmTokenRequest"];
            };
        };
        responses: {
            /** @description Token atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token não enviado */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_my_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_motoristas: {
        parameters: {
            query?: never;
            header?: {
                /** @description An optional fields mask */
                "X-Fields"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"][];
                };
            };
            /** @description Forbidden - not a gestor */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_motorista: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MotoristaCreateRequest"];
            };
        };
        responses: {
            /** @description Motorista created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not a gestor */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description O UUID do usuário */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_all_viagens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViagemListResponse"];
                };
            };
        };
    };
    create_viagem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViagemCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViagemResponse"];
                };
            };
        };
    };
    list_viagens_aluno: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViagemAgendaAlunoListResponse"];
                };
            };
        };
    };
    gerar_viagens_lote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViagemLoteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViagemLoteResponse"];
                };
            };
        };
    };
    list_my_viagens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViagemListResponse"];
                };
            };
        };
    };
    control_viagem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViagemAcaoRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViagemResponse"];
                };
            };
        };
    };
    cancelar_viagem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmar_presenca: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViagemConfirmacaoRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViagemAlunoConfirmacaoResponse"];
                };
            };
        };
    };
    obter_localizacao_onibus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    atualizar_localizacao_onibus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LocalizacaoRequest"];
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_pontos_embarque_viagem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoFlatListResponse"];
                };
            };
        };
    };
    atualizar_localizacao_aluno: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viagem_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LocalizacaoRequest"];
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
