name: Android Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: ./.github/workflows/_android-build-reusable.yml
    with:
      GRADLE_PARAMS: Release
      VERSION_NAME: ${{ github.ref_name }}
      SHOULD_GRADLE_CLEAN: 'true'
      CREATE_GITHUB_RELEASE: true
      DISCORD_MODE: release
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_RELEASES }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      API_URL_PRODUCTION: ${{ secrets.API_URL_PRODUCTION }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}