name: Android Build APK

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main, release/* ]
  workflow_dispatch:
    inputs:
      GRADLE_PARAMS:
        description: 'Gradle parameters for the build'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release
      VERSION_NAME:
        description: 'Version name (Optional - ex: 1.0.0)'
        required: false
        default: ''
      SHOULD_GRADLE_CLEAN:
        description: 'Should run gradle clean before build'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    uses: ./.github/workflows/_android-build-reusable.yml
    with:
      GRADLE_PARAMS: ${{ inputs.GRADLE_PARAMS || 'Release' }}
      VERSION_NAME: ${{ inputs.VERSION_NAME || '' }}
      SHOULD_GRADLE_CLEAN: ${{ inputs.SHOULD_GRADLE_CLEAN || 'false' }}
      CREATE_GITHUB_RELEASE: false
      DISCORD_MODE: build
    secrets:
      DISCORD_WEBHOOK_CI: ${{ secrets.DISCORD_WEBHOOK_CI }}
      API_URL_PRODUCTION: ${{ secrets.API_URL_PRODUCTION }}
      API_URL_DEVELOPMENT: ${{ secrets.API_URL_DEVELOPMENT }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}